#! /bin/sh

set -e

if ! id -u minimega >/dev/null 2>&1; then
    echo "Adding minimega user."
    useradd --system --no-create-home --home-dir /run/minimega minimega
else
    echo "minimega user already exists."
fi

chown -R minimega:minimega /usr/share/doc/minimega
chown -R minimega:minimega /opt/minimega
chown -R minimega:minimega /etc/minimega

# Symlink all binaries

# Generate and install the bash tab-completion script as part of a standard
# install, so users don't need to run 'minimega -completion' manually.
if [ -x /usr/bin/minimega ]; then
    mkdir -p /usr/share/bash-completion/completions
    /usr/bin/minimega -completion bash > /usr/share/bash-completion/completions/minimega
fi

#DEBHELPER#
