// Copyright (2024) Sandia Corporation.
// Under the terms of Contract DE-AC04-94AL85000 with Sandia Corporation,
// the U.S. Government retains certain rights in this software.

package main

import (
	"flag"
	"fmt"
	"sort"
	"strings"
)

// bashCompletionTemplate is the bash-completion script printed by
// `minimega -completion`. The `%s` is replaced with a space-separated list of
// minimega's flags, generated at runtime from flag.CommandLine so that the
// script always stays in sync with the flags the binary actually supports.
//
// Completion of minicli commands (e.g. after `-e` or `-attach`) is delegated
// back to minimega itself via the hidden `-suggest` flag, which reuses the
// same minicli.Suggest logic that powers tab completion in the interactive
// minimega prompt.
const bashCompletionTemplate = `# bash completion for minimega                            -*- shell-script -*-
#
# Generated by 'minimega -completion'. To enable minimega tab completion for
# the current shell session:
#
#   source <(minimega -completion)
#
# To enable it for every session, write the script somewhere bash-completion
# will find it, e.g.:
#
#   minimega -completion | sudo tee /etc/bash_completion.d/minimega >/dev/null

_minimega_completion() {
    local cur words cword
    words=("${COMP_WORDS[@]}")
    cword=$COMP_CWORD
    cur="${words[cword]}"

    COMPREPLY=()

    # if -e or -attach appears earlier on the command line, everything from
    # that point on is a minicli command (not a minimega flag), so ask
    # minimega itself for suggestions instead of completing flags/files
    local i cmd_start=-1
    for (( i = 1; i < cword; i++ )); do
        case "${words[i]}" in
            -e|-attach)
                cmd_start=$((i + 1))
                ;;
        esac
    done

    if [[ $cmd_start -ge 0 ]]; then
        # rebuild the partial minicli command from the words following
        # -e/-attach; a trailing space (from an empty final word) tells
        # minimega the previous token is complete
        local partial="" sep="" j
        for (( j = cmd_start; j <= cword; j++ )); do
            partial+="${sep}${words[j]}"
            sep=" "
        done

        local suggestions
        suggestions=$(minimega -suggest "$partial" 2>/dev/null)
        COMPREPLY=( $(compgen -W "${suggestions}" -- "") )
        return 0
    fi

    # otherwise, complete minimega's own flags and/or filenames; compgen
    # naturally narrows both lists down based on $cur (including the empty
    # string, which matches everything)
    local flags files
    flags=( $(compgen -W "%s" -- "$cur") )
    files=( $(compgen -f -- "$cur") )

    if [[ ${#files[@]} -gt 0 ]]; then
        compopt -o filenames 2>/dev/null
    fi

    COMPREPLY=( "${flags[@]}" "${files[@]}" )
}

complete -F _minimega_completion minimega
`

// bashCompletion returns a bash-completion script for minimega.
func bashCompletion() string {
	var names []string
	flag.VisitAll(func(f *flag.Flag) {
		names = append(names, "-"+f.Name)
	})
	sort.Strings(names)

	return fmt.Sprintf(bashCompletionTemplate, strings.Join(names, " "))
}
