// Copyright 2026 National Technology & Engineering Solutions of Sandia, LLC (NTESS).
// Under the terms of Contract DE-NA0003525 with NTESS, the U.S. Government retains certain
// rights in this software.

package main

import (
	"flag"
	"fmt"
	"sort"
	"strings"
)

// bashCompletionTemplate is the bash-completion script printed by
// `minimega -completion bash`. The `%[1]s` is replaced with a
// space-separated list of minimega's flags, generated at runtime from
// flag.CommandLine so that the script always stays in sync with the flags
// the binary actually supports.
//
// Completion of minicli commands (e.g. after `-e` or `-attach`) is delegated
// back to minimega itself via the hidden `-suggest` flag, which reuses the
// same minicli.Suggest logic that powers tab completion in the interactive
// minimega prompt.
const bashCompletionTemplate = `# bash completion for minimega                            -*- shell-script -*-
#
# Generated by 'minimega -completion bash'. To enable minimega tab completion
# for the current shell session:
#
#   source <(minimega -completion bash)
#
# To enable it for every session, write the script somewhere bash-completion
# will find it, e.g.:
#
#   minimega -completion bash | sudo tee /usr/share/bash-completion/completions/minimega >/dev/null
#
# or, on older systems without a /usr/share/bash-completion/completions
# directory:
#
#   minimega -completion bash | sudo tee /etc/bash_completion.d/minimega >/dev/null

_minimega_completion() {
    local cur words cword
    words=("${COMP_WORDS[@]}")
    cword=$COMP_CWORD
    cur="${words[cword]}"

    COMPREPLY=()

    # if -e or -attach appears earlier on the command line, everything from
    # that point on is a minicli command (not a minimega flag), so ask
    # minimega itself for suggestions instead of completing flags/files
    local i cmd_start=-1
    for (( i = 1; i < cword; i++ )); do
        case "${words[i]}" in
            -e|-attach)
                cmd_start=$((i + 1))
                ;;
        esac
    done

    if [[ $cmd_start -ge 0 ]]; then
        # rebuild the partial minicli command from the words following
        # -e/-attach; a trailing space (from an empty final word) tells
        # minimega the previous token is complete
        local partial="" sep="" j
        for (( j = cmd_start; j <= cword; j++ )); do
            partial+="${sep}${words[j]}"
            sep=" "
        done

        local suggestions
        suggestions=$(minimega -suggest "$partial" 2>/dev/null)
        COMPREPLY=( $(compgen -W "${suggestions}" -- "") )
        return 0
    fi

    # otherwise, complete minimega's own flags and/or filenames; compgen
    # naturally narrows both lists down based on $cur (including the empty
    # string, which matches everything)
    local flags files
    flags=( $(compgen -W "%[1]s" -- "$cur") )
    files=( $(compgen -f -- "$cur") )

    if [[ ${#files[@]} -gt 0 ]]; then
        compopt -o filenames 2>/dev/null
    fi

    COMPREPLY=( "${flags[@]}" "${files[@]}" )
}

complete -F _minimega_completion minimega
`

// zshCompletionTemplate is the zsh-completion script printed by
// `minimega -completion zsh`. The `%[1]s` is replaced with a
// space-separated list of minimega's flags, the same as in
// bashCompletionTemplate.
//
// Like the bash version, completion of minicli commands typed after
// `-e`/`-attach` is delegated back to minimega via the hidden `-suggest`
// flag.
const zshCompletionTemplate = `#compdef minimega
# zsh completion for minimega                              -*- shell-script -*-
#
# Generated by 'minimega -completion zsh'. To enable minimega tab completion
# for the current shell session:
#
#   source <(minimega -completion zsh)
#
# To enable it for every session, write the script somewhere your zsh
# 'fpath' will find it (a directory searched by 'compinit'), e.g.:
#
#   minimega -completion zsh | sudo tee /usr/share/zsh/site-functions/_minimega >/dev/null

_minimega() {
    local cur=${words[CURRENT]}

    # if -e or -attach appears earlier on the command line, everything from
    # that point on is a minicli command (not a minimega flag), so ask
    # minimega itself for suggestions instead of completing flags/files
    local i cmd_start=-1
    for (( i = 2; i < CURRENT; i++ )); do
        case ${words[i]} in
            -e|-attach)
                cmd_start=$((i + 1))
                ;;
        esac
    done

    if (( cmd_start >= 2 )); then
        # rebuild the partial minicli command from the words following
        # -e/-attach; a trailing space (from an empty final word) tells
        # minimega the previous token is complete
        local partial="" sep="" j
        for (( j = cmd_start; j < CURRENT; j++ )); do
            partial+="${sep}${words[j]}"
            sep=" "
        done

        local -a suggestions
        suggestions=(${(f)"$(minimega -suggest "$partial" 2>/dev/null)"})
        compadd -a suggestions
        return
    fi

    # otherwise, complete minimega's own flags and/or filenames
    local -a flags
    flags=(%[1]s)
    compadd -a flags
    _files
}

# if this script was loaded the normal zsh way -- as an autoloaded function
# file named '_minimega' somewhere in 'fpath', picked up by 'compinit' -- the
# '#compdef' line above already registered it. Otherwise (e.g. when directly
# sourced via 'source <(minimega -completion zsh)') register it manually.
if [[ "$(basename -- "${(%%):-%%x}")" != "_minimega" ]]; then
    compdef _minimega minimega
fi
`

// fishCompletionTemplate is the fish-completion script printed by
// `minimega -completion fish`. The `%[1]s` is replaced with a block of
// `complete` statements, one per minimega flag, generated at runtime from
// flag.CommandLine so the script always stays in sync with the flags the
// binary actually supports.
//
// Like the bash and zsh versions, completion of minicli commands typed
// after `-e`/`-attach` is delegated back to minimega via the hidden
// `-suggest` flag. Flag completions are left to fish's default file
// completion behavior when no `-e`/`-attach` is present on the command
// line, since `complete` only suppresses file completion for the specific
// invocation it's attached to.
const fishCompletionTemplate = `# fish completion for minimega                             -*- shell-script -*-
#
# Generated by 'minimega -completion fish'. To enable minimega tab
# completion for the current shell session:
#
#   minimega -completion fish | source
#
# To enable it for every session, write the script somewhere fish will find
# it, e.g.:
#
#   minimega -completion fish | sudo tee /usr/share/fish/vendor_completions.d/minimega.fish >/dev/null

function __minimega_needs_suggest
    set -l cmd (commandline -opc)
    for c in $cmd
        switch $c
            case -e -attach
                return 0
        end
    end
    return 1
end

function __minimega_suggest
    set -l cmd (commandline -opc)
    set -l cur (commandline -ct)

    # if -e or -attach appears earlier on the command line, everything from
    # that point on is a minicli command (not a minimega flag), so ask
    # minimega itself for suggestions instead of completing flags/files
    set -l cmd_start 0
    for i in (seq (count $cmd))
        switch $cmd[$i]
            case -e -attach
                set cmd_start (math $i + 1)
        end
    end

    if test $cmd_start -eq 0
        return
    end

    # rebuild the partial minicli command from the words following
    # -e/-attach, plus the word currently being completed; a trailing
    # space (from an empty final word) tells minimega the previous token
    # is complete
    set -l partial
    if test $cmd_start -le (count $cmd)
        set partial (string join ' ' $cmd[$cmd_start..-1])" $cur"
    else
        set partial $cur
    end

    minimega -suggest "$partial" 2>/dev/null
end

complete -c minimega -f -n __minimega_needs_suggest -a '(__minimega_suggest)'

%[1]s`

// supportedShells is the set of shells -completion accepts, used both for
// validation and for the flag's usage/help text.
var supportedShells = []string{"bash", "zsh", "fish"}

// completionTemplates maps each supported shell name to its script template.
var completionTemplates = map[string]string{
	"bash": bashCompletionTemplate,
	"zsh":  zshCompletionTemplate,
	"fish": fishCompletionTemplate,
}

// completionFlagArgs maps each supported shell name to a function that
// renders minimega's sorted, bare (no leading dash) flag names into
// whatever syntax that shell's completion template expects for the %[1]s
// substitution.
var completionFlagArgs = map[string]func(names []string) string{
	"bash": spaceSeparatedDashedFlags,
	"zsh":  spaceSeparatedDashedFlags,
	"fish": fishFlagCompletions,
}

// spaceSeparatedDashedFlags renders flag names as a single space-separated
// string of dash-prefixed flags, e.g. "-base -degree -force", suitable for
// bash's compgen -W and zsh's compadd -a.
func spaceSeparatedDashedFlags(names []string) string {
	dashed := make([]string, len(names))
	for i, n := range names {
		dashed[i] = "-" + n
	}
	return strings.Join(dashed, " ")
}

// fishFlagCompletions renders one 'complete' statement per flag, using
// fish's "old style" single-dash option syntax (-o) since minimega's flags
// are single-dash but multi-character (e.g. -base), not fish's usual
// double-dash long options.
func fishFlagCompletions(names []string) string {
	var b strings.Builder
	for i, n := range names {
		if i > 0 {
			b.WriteString("\n")
		}
		fmt.Fprintf(&b, "complete -c minimega -n 'not __minimega_needs_suggest' -o %s -d 'minimega flag'", n)
	}
	return b.String()
}

// shellCompletion returns a tab-completion script for minimega for the
// given shell (one of supportedShells), or an error if the shell isn't
// supported.
func shellCompletion(shell string) (string, error) {
	tmpl, ok := completionTemplates[shell]
	if !ok {
		return "", fmt.Errorf("unsupported shell %q for -completion (supported: %s)", shell, strings.Join(supportedShells, ", "))
	}

	var names []string
	flag.VisitAll(func(f *flag.Flag) {
		names = append(names, f.Name)
	})
	sort.Strings(names)

	return fmt.Sprintf(tmpl, completionFlagArgs[shell](names)), nil
}
