name: "Bug report"
description: Describe a bug, error, unexpected behavior, or other problem
labels:
  - bug

body:
  - type: input
    attributes:
      label: minimega version
      description: Which version/commit of minimega are you using?
    validations:
      required: true
  - type: input
    attributes:
      label: Linux distro/version
      description: Which Linux distro and version are you running minimega on?
    validations:
      required: true
  - type: input
    attributes:
      label: Go compiler version
      description: If you compiled minimega, which version of go was used?
  - type: textarea
    attributes:
      label: Summary
      description: What's wrong? If the issue is related to a VM, provide details for the VM (type, OS, etc.)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior. Any helpful log output or screenshots?
      placeholder: |
        1. Do this
        2. Then this

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: What did you expect to happen that didn't?
    validations:
      required: true