name: "Submit a feature request / idea"
description: Describe an idea, feature, or improvement
labels:
  - enhancement

body:
  - type: textarea
    attributes:
      label: Summary
      description: What is the work, and why should it be added?
      placeholder: |
        The purpose of this issue is to accomplish x task for y reason...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Implementation notes
      description: Please provide details for implementation.
      placeholder: |
        1. An example for how this would be used
        2. What would this look like
        3. How this would act
        4. Any related work, including links to related issues
    validations:
      required: true
  - type: textarea
    attributes:
      label: Acceptance criteria
      description: How do we know when this work is done?
      placeholder: |
        - [ ] The new feature is fully implemented based on x, y, z criteria
        - [ ] Additional unit test coverage is added
        - [ ] Any other criteria
    validations:
      required: true