#!/bin/sh

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs udev /dev
mkdir /dev/pts
mount -n -t devpts -o gid=5,mode=620 none /dev/pts
udevd --daemon
udevadm trigger
udevadm settle

ifconfig eth0 up
dhclient -v eth0

mkdir /var/run/sshd
/usr/sbin/sshd

exec /bin/sh
