version: '3.7'
services:
  minimega:
    image: minimega
    container_name: minimega
    hostname: minimega
    privileged: true
    cap_add:
    - ALL
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    ports:
    - 9000:9000/udp
    - 9001:9001
    volumes:
    - /dev:/dev
    - /lib/modules:/lib/modules:ro
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
    - /etc/localtime:/etc/localtime:ro
    - /tmp/minimega:/tmp/minimega
    - /var/log/minimega:/var/log/minimega
    - /root/.ssh:/root/.ssh:ro
    healthcheck:
      test: minimega -e version
