#! /bin/sh

set -e

if ! id -u minimega >/dev/null 2>&1; then
    echo "Adding minimega user."
    adduser --quiet --system --group --no-create-home --home /run/minimega \
        --gecos "minimega user" minimega
else
    echo "minimega user already exists."
fi

sudo chown -R minimega:minimega /usr/share/doc/minimega
sudo chown -R minimega:minimega /opt/minimega
