#!/bin/sh

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

ifconfig lo up

mkdir /var/run/sshd
/usr/sbin/sshd &

/etc/init.d/bird start
/miniccc -family unix -parent /cc -logfile /miniccc.log &

bash
