#!/bin/sh

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs udev /dev
mkdir /dev/pts
mount -n -t devpts -o gid=5,mode=620 none /dev/pts
udevd --daemon
udevadm trigger
udevadm settle
chmod a+rx /

ifconfig eth0 up 10.0.0.1 netmask 255.255.0.0
ifconfig eth1 up 11.0.0.1 netmask 255.255.0.0

mkdir /var/run/sshd
/usr/sbin/sshd

/etc/init.d/quagga start

exec </dev/tty1 >/dev/tty1 2&1
exec sh

