// Trimmed subset of the Android Emulator gRPC controller proto.
// Only includes RPCs and messages needed for screenshot streaming and input.
//
// Upstream: https://android.googlesource.com/platform/external/qemu/+/refs/heads/emu-master-dev/android/android-grpc/
// See LICENSES/LICENSE.android-emulator-proto for the full license text.
//
// Copyright (C) 2018 The Android Open Source Project
// Licensed under the Apache License, Version 2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: emulator_controller.proto

package emupb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EmulatorController_GetScreenshot_FullMethodName    = "/android.emulation.control.EmulatorController/getScreenshot"
	EmulatorController_StreamScreenshot_FullMethodName = "/android.emulation.control.EmulatorController/streamScreenshot"
	EmulatorController_SendKey_FullMethodName          = "/android.emulation.control.EmulatorController/sendKey"
	EmulatorController_SendTouch_FullMethodName        = "/android.emulation.control.EmulatorController/sendTouch"
	EmulatorController_SendMouse_FullMethodName        = "/android.emulation.control.EmulatorController/sendMouse"
	EmulatorController_GetStatus_FullMethodName        = "/android.emulation.control.EmulatorController/getStatus"
	EmulatorController_SetPhysicalModel_FullMethodName = "/android.emulation.control.EmulatorController/setPhysicalModel"
	EmulatorController_SetGps_FullMethodName           = "/android.emulation.control.EmulatorController/setGps"
	EmulatorController_InjectWheel_FullMethodName      = "/android.emulation.control.EmulatorController/injectWheel"
	EmulatorController_GetLogcat_FullMethodName        = "/android.emulation.control.EmulatorController/getLogcat"
)

// EmulatorControllerClient is the client API for EmulatorController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmulatorControllerClient interface {
	GetScreenshot(ctx context.Context, in *ImageFormat, opts ...grpc.CallOption) (*Image, error)
	StreamScreenshot(ctx context.Context, in *ImageFormat, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Image], error)
	SendKey(ctx context.Context, in *KeyboardEvent, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SendTouch(ctx context.Context, in *TouchEvent, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SendMouse(ctx context.Context, in *MouseEvent, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*EmulatorStatus, error)
	SetPhysicalModel(ctx context.Context, in *PhysicalModelValue, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SetGps(ctx context.Context, in *GpsState, opts ...grpc.CallOption) (*emptypb.Empty, error)
	InjectWheel(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WheelEvent, emptypb.Empty], error)
	GetLogcat(ctx context.Context, in *LogMessage, opts ...grpc.CallOption) (*LogMessage, error)
}

type emulatorControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewEmulatorControllerClient(cc grpc.ClientConnInterface) EmulatorControllerClient {
	return &emulatorControllerClient{cc}
}

func (c *emulatorControllerClient) GetScreenshot(ctx context.Context, in *ImageFormat, opts ...grpc.CallOption) (*Image, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Image)
	err := c.cc.Invoke(ctx, EmulatorController_GetScreenshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) StreamScreenshot(ctx context.Context, in *ImageFormat, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Image], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EmulatorController_ServiceDesc.Streams[0], EmulatorController_StreamScreenshot_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ImageFormat, Image]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmulatorController_StreamScreenshotClient = grpc.ServerStreamingClient[Image]

func (c *emulatorControllerClient) SendKey(ctx context.Context, in *KeyboardEvent, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EmulatorController_SendKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) SendTouch(ctx context.Context, in *TouchEvent, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EmulatorController_SendTouch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) SendMouse(ctx context.Context, in *MouseEvent, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EmulatorController_SendMouse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) GetStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*EmulatorStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmulatorStatus)
	err := c.cc.Invoke(ctx, EmulatorController_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) SetPhysicalModel(ctx context.Context, in *PhysicalModelValue, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EmulatorController_SetPhysicalModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) SetGps(ctx context.Context, in *GpsState, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EmulatorController_SetGps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) InjectWheel(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WheelEvent, emptypb.Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EmulatorController_ServiceDesc.Streams[1], EmulatorController_InjectWheel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WheelEvent, emptypb.Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmulatorController_InjectWheelClient = grpc.ClientStreamingClient[WheelEvent, emptypb.Empty]

func (c *emulatorControllerClient) GetLogcat(ctx context.Context, in *LogMessage, opts ...grpc.CallOption) (*LogMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogMessage)
	err := c.cc.Invoke(ctx, EmulatorController_GetLogcat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmulatorControllerServer is the server API for EmulatorController service.
// All implementations must embed UnimplementedEmulatorControllerServer
// for forward compatibility.
type EmulatorControllerServer interface {
	GetScreenshot(context.Context, *ImageFormat) (*Image, error)
	StreamScreenshot(*ImageFormat, grpc.ServerStreamingServer[Image]) error
	SendKey(context.Context, *KeyboardEvent) (*emptypb.Empty, error)
	SendTouch(context.Context, *TouchEvent) (*emptypb.Empty, error)
	SendMouse(context.Context, *MouseEvent) (*emptypb.Empty, error)
	GetStatus(context.Context, *emptypb.Empty) (*EmulatorStatus, error)
	SetPhysicalModel(context.Context, *PhysicalModelValue) (*emptypb.Empty, error)
	SetGps(context.Context, *GpsState) (*emptypb.Empty, error)
	InjectWheel(grpc.ClientStreamingServer[WheelEvent, emptypb.Empty]) error
	GetLogcat(context.Context, *LogMessage) (*LogMessage, error)
	mustEmbedUnimplementedEmulatorControllerServer()
}

// UnimplementedEmulatorControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmulatorControllerServer struct{}

func (UnimplementedEmulatorControllerServer) GetScreenshot(context.Context, *ImageFormat) (*Image, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScreenshot not implemented")
}
func (UnimplementedEmulatorControllerServer) StreamScreenshot(*ImageFormat, grpc.ServerStreamingServer[Image]) error {
	return status.Errorf(codes.Unimplemented, "method StreamScreenshot not implemented")
}
func (UnimplementedEmulatorControllerServer) SendKey(context.Context, *KeyboardEvent) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendKey not implemented")
}
func (UnimplementedEmulatorControllerServer) SendTouch(context.Context, *TouchEvent) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTouch not implemented")
}
func (UnimplementedEmulatorControllerServer) SendMouse(context.Context, *MouseEvent) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMouse not implemented")
}
func (UnimplementedEmulatorControllerServer) GetStatus(context.Context, *emptypb.Empty) (*EmulatorStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedEmulatorControllerServer) SetPhysicalModel(context.Context, *PhysicalModelValue) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPhysicalModel not implemented")
}
func (UnimplementedEmulatorControllerServer) SetGps(context.Context, *GpsState) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetGps not implemented")
}
func (UnimplementedEmulatorControllerServer) InjectWheel(grpc.ClientStreamingServer[WheelEvent, emptypb.Empty]) error {
	return status.Errorf(codes.Unimplemented, "method InjectWheel not implemented")
}
func (UnimplementedEmulatorControllerServer) GetLogcat(context.Context, *LogMessage) (*LogMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLogcat not implemented")
}
func (UnimplementedEmulatorControllerServer) mustEmbedUnimplementedEmulatorControllerServer() {}
func (UnimplementedEmulatorControllerServer) testEmbeddedByValue()                            {}

// UnsafeEmulatorControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmulatorControllerServer will
// result in compilation errors.
type UnsafeEmulatorControllerServer interface {
	mustEmbedUnimplementedEmulatorControllerServer()
}

func RegisterEmulatorControllerServer(s grpc.ServiceRegistrar, srv EmulatorControllerServer) {
	// If the following call pancis, it indicates UnimplementedEmulatorControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EmulatorController_ServiceDesc, srv)
}

func _EmulatorController_GetScreenshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageFormat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).GetScreenshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_GetScreenshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).GetScreenshot(ctx, req.(*ImageFormat))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_StreamScreenshot_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ImageFormat)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EmulatorControllerServer).StreamScreenshot(m, &grpc.GenericServerStream[ImageFormat, Image]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmulatorController_StreamScreenshotServer = grpc.ServerStreamingServer[Image]

func _EmulatorController_SendKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyboardEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).SendKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_SendKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).SendKey(ctx, req.(*KeyboardEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_SendTouch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TouchEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).SendTouch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_SendTouch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).SendTouch(ctx, req.(*TouchEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_SendMouse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MouseEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).SendMouse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_SendMouse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).SendMouse(ctx, req.(*MouseEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).GetStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_SetPhysicalModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PhysicalModelValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).SetPhysicalModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_SetPhysicalModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).SetPhysicalModel(ctx, req.(*PhysicalModelValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_SetGps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GpsState)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).SetGps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_SetGps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).SetGps(ctx, req.(*GpsState))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_InjectWheel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EmulatorControllerServer).InjectWheel(&grpc.GenericServerStream[WheelEvent, emptypb.Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmulatorController_InjectWheelServer = grpc.ClientStreamingServer[WheelEvent, emptypb.Empty]

func _EmulatorController_GetLogcat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).GetLogcat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_GetLogcat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).GetLogcat(ctx, req.(*LogMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// EmulatorController_ServiceDesc is the grpc.ServiceDesc for EmulatorController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmulatorController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "android.emulation.control.EmulatorController",
	HandlerType: (*EmulatorControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getScreenshot",
			Handler:    _EmulatorController_GetScreenshot_Handler,
		},
		{
			MethodName: "sendKey",
			Handler:    _EmulatorController_SendKey_Handler,
		},
		{
			MethodName: "sendTouch",
			Handler:    _EmulatorController_SendTouch_Handler,
		},
		{
			MethodName: "sendMouse",
			Handler:    _EmulatorController_SendMouse_Handler,
		},
		{
			MethodName: "getStatus",
			Handler:    _EmulatorController_GetStatus_Handler,
		},
		{
			MethodName: "setPhysicalModel",
			Handler:    _EmulatorController_SetPhysicalModel_Handler,
		},
		{
			MethodName: "setGps",
			Handler:    _EmulatorController_SetGps_Handler,
		},
		{
			MethodName: "getLogcat",
			Handler:    _EmulatorController_GetLogcat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "streamScreenshot",
			Handler:       _EmulatorController_StreamScreenshot_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "injectWheel",
			Handler:       _EmulatorController_InjectWheel_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "emulator_controller.proto",
}
