#!/bin/sh

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs udev /dev
mkdir /dev/pts
mount -n -t devpts -o gid=5,mode=620 none /dev/pts
udevd --daemon
udevadm trigger
udevadm settle
chmod a+rx /

ifconfig lo up

ETH0=`awk 'BEGIN {RS = " "} ; {split($1,a,"="); if (a[1] == "eth0") {print a[2]; }}' /proc/cmdline`
ETH1=`awk 'BEGIN {RS = " "} ; {split($1,a,"="); if (a[1] == "eth1") {print a[2]; }}' /proc/cmdline`
ifconfig eth0 up $ETH0 netmask 255.255.0.0
ifconfig eth1 up $ETH1 netmask 255.255.0.0

mkdir /var/run/sshd
/usr/sbin/sshd

NET0=`awk 'BEGIN {RS = " "} ; {split($1,a,"="); if (a[1] == "NET0") {print a[2]; }}' /proc/cmdline`
NET1=`awk 'BEGIN {RS = " "} ; {split($1,a,"="); if (a[1] == "NET1") {print a[2]; }}' /proc/cmdline`
sed -i s#NET0#$NET0# /etc/quagga/ospfd.conf
sed -i s#NET1#$NET1# /etc/quagga/ospfd.conf
/etc/init.d/quagga start

setsid sh -c 'exec sh </dev/tty1 >/dev/tty1 2>&1'
