// Copyright (2016) Sandia Corporation.
// Under the terms of Contract DE-AC04-94AL85000 with Sandia Corporation,
// the U.S. Government retains certain rights in this software.

package main

var defaultMessages = []string{
	"Lorem ipsum dolor sit amet, eum omnes ornatus volumus id.",
	"Eam in tamquam nostrud volutpat.",
	"Nec sonet similique definiebas et, sit eu vero vituperatoribus.",
	"Sed ipsum moderatius suscipiantur no, est amet enim virtute cu, dolore maiestatis cu mei.",
	"Mei harum alterum antiopam eu, eros nominavi ad his.",
	"Pri an iracundia reformidans, vix no quod officiis oporteat.",
	"Omnium deleniti mei at.Inermis fuisset vis id, ea harum utamur vim, eam no numquam facilisis iudicabit.",
	"Eam senserit sententiae voluptatibus no, ius te vero prodesset temporibus, mel no debet partem melius.",
	"Duo id choro vivendum, ad veri alienum mea, natum nostro aperiam usu ad.",
	"Sit dicunt conceptam suscipiantur eu.Ei meis cetero usu, sit cu tempor appellantur.",
	"At has oporteat eleifend mediocrem.",
	"Sumo simul omittam te quo, populo disputationi quo at.",
	"Eum feugiat suscipiantur an.",
	"Clita adversarium contentiones cu duo, libris scripta aliquam eu vis, cum ea expetendis dissentias.Ius ne homero iracundia abhorreant, reque deserunt ad has.",
	"At vix graece discere accusamus, ut persius deserunt suscipiantur eum.",
	"Assum nihil rationibus est cu.",
	"Affert complectitur consectetuer ut eos, mei ex essent definitiones.",
	"Altera percipit electram ea ius, vitae doctus eu eum.Pri enim viris elitr id.",
	"Nec id persius consulatu vulputate, at porro alienum est.",
	"Modus zril partiendo ne ius, sea vocibus consequat quaerendum no, ius no atqui voluptua.",
	"Ei alterum explicari pri, sed omnesque perfecto singulis id, legimus ullamcorper has ei.",
	"His hinc quaerendum persequeris ea, eos eu singulis mnesarchum.Ne pri eligendi appareat apeirian, ad sed ancillae periculis molestiae.",
	"Et nec ullum senserit vituperata, odio detraxit philosophia ei vel.",
	"Pri commodo convenire ei, exerci referrentur sea ne.",
	"Qui mazim adipisci consequuntur ei, idque dicunt ea eos.Has te purto omnium conceptam, et sonet tation volutpat pri, nec magna commune in.",
	"Natum omnes cum eu, amet ipsum quodsi ius eu.",
	"Dicunt copiosae assueverit at vel, elaboraret interesset vel ut.",
	"Ne eos facer dolore, no quo nisl everti commodo.",
	"Per probo mollis inciderint ad, minim tritani impedit eum an.Sea no ullum oportere inciderint.",
	"Assum aperiam adversarium et sea, nec ex ubique nostrum.",
	"Mutat copiosae persecuti has in, dicat lobortis ut eum.",
	"Duo meliore appetere ne.",
	"Cu duis aeterno corpora vix, veniam fastidii recteque vim id, quo adolescens assueverit disputando id.Amet vocibus eos ne.",
	"Pro idque facer praesent ne, saepe admodum recteque qui at.",
	"Et case latine vel, diam habemus per id, id per libris virtute.",
	"Posse tollit alienum ius eu, id nec audiam copiosae reprehendunt.Id timeam veritus duo, cu usu quaeque discere.",
	"Probatus percipitur et usu.",
	"Mandamus salutandi ex nam, porro vitae legimus nec ex.",
	"Stet velit definitionem no sit, id his agam nonumy possim.",
	"Facer zril intellegat no sed, ne pri augue delectus splendide, sed ea iuvaret deleniti.",
	"At nusquam omittam sensibus qui, ei mel rebum minim deleniti, illum congue antiopam ne per.",
}

var defaultNicks = []string{
	"theron",
	"thaddeus",
	"seth",
	"perry",
	"brendan",
	"porfirio",
	"jerald",
	"shayne",
	"gino",
	"rickey",
	"elmer",
	"cameron",
	"drew",
	"lucio",
	"francis",
	"christian",
	"jerrell",
	"dirk",
	"jere",
	"kelley",
	"jaimie",
	"holli",
	"larissa",
	"sarah",
	"sophia",
	"terrilyn",
	"stacia",
	"sindy",
	"josphine",
	"janae",
	"violette",
	"gabriella",
	"mellie",
	"asha",
	"vickie",
	"evelynn",
	"clora",
	"linsey",
	"gianna",
	"emelda",
}
