#!/bin/sh

export PATH

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs udev /dev
mkdir /dev/pts
mount -n -t devpts -o gid=5,mode=620 none /dev/pts
udevd --daemon
udevadm trigger
udevadm settle
chmod a+rx /
mount /dev/sda1 /scratch
modprobe loop
modprobe tun
modprobe nbd max_part=10
modprobe kvm-intel

ulimit -n 999999

modprobe bonding
for i in `ls /sys/class/net | grep eth10G`;
do
	ifenslave bond0 $i
done

modprobe openvswitch_mod
/etc/init.d/openvswitch-switch start
ovs-vsctl add-br mega_bridge
ovs-vsctl set Bridge mega_bridge stp_enable=false
#ovs-vsctl add-port mega_bridge eth10G
ovs-vsctl add-port mega_bridge bond0
ifconfig lo up
#ifconfig eth10G up 0.0.0.0
ifconfig bond0 up 0.0.0.0
dhclient -v mega_bridge
dhclient -v eth0

mkdir /var/run/sshd
/usr/sbin/sshd

echo 32768 > /proc/sys/net/ipv4/neigh/default/gc_thresh1
echo 32768 > /proc/sys/net/ipv4/neigh/default/gc_thresh2
echo 65536 > /proc/sys/net/ipv4/neigh/default/gc_thresh3
echo 32768 > /proc/sys/net/ipv6/neigh/default/gc_thresh1
echo 32768 > /proc/sys/net/ipv6/neigh/default/gc_thresh2
echo 65536 > /proc/sys/net/ipv6/neigh/default/gc_thresh3


setsid sh -c 'exec sh </dev/tty1 >/dev/tty1 2>&1'
