#!/bin/sh

export PATH

# mount volatile filesystems
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs udev /dev
mkdir /dev/pts
mount -n -t devpts -o newinstance,ptmxmode=666,gid=5,mode=620 none /dev/pts
rm /dev/ptmx
ln -s /dev/pts/ptmx /dev/ptmx
mount -t tmpfs cgroup /sys/fs/cgroup
mkdir /sys/fs/cgroup/memory
mkdir /sys/fs/cgroup/freezer
mkdir /sys/fs/cgroup/devices
mount -t cgroup cgroup -o memory /sys/fs/cgroup/memory
mount -t cgroup cgroup -o freezer /sys/fs/cgroup/freezer
mount -t cgroup cgroup -o devices /sys/fs/cgroup/devices

# / needs permissions!?
chmod a+rx /

# minimega needs
modprobe igb
modprobe ixgbe
modprobe mlx4_core
modprobe loop
modprobe tun
modprobe nbd max_part=10
modprobe kvm-intel

# local disks
modprobe sd
modprobe sd_mod
modprobe scsi_transport_sas
modprobe scsi_mod
modprobe libata
modprobe ext4
modprobe libsas
modprobe ahci
modprobe isci

# settle :(
sleep 10

# local disk for scratch
mount /dev/sda1 /scratch

# bump open file handle limits
ulimit -n 999999

# bond all 10G/40G interfaces
for i in `ls /sys/class/net`
do
        G=`ls -l /sys/class/net/$i/device/driver 2>/dev/null | grep -e "ixgbe" -e "mlx4_core"`
        if [ -n "$G" ]
        then
                NETS="$NETS $i"
		ifconfig $i up
        fi
done

echo "bonding nets $NETS"

# setup a minimega bridge with the 10G interface trunked and bring up other interfaces
modprobe openvswitch_mod
/etc/init.d/openvswitch-switch start
ovs-vsctl add-br mega_bridge
ovs-vsctl set Bridge mega_bridge stp_enable=false
numnets=`echo $NETS | wc -w`
if [ $numnets -eq 1 ]
then
	ovs-vsctl add-port mega_bridge $NETS
else
	ovs-vsctl add-bond mega_bridge bond0 $NETS lacp=active
	ovs-vsctl set port bond0 bond_mode=balance-tcp  
fi

ifconfig lo up
dhclient -v mega_bridge
dhclient -v eth0

# ssh
mkdir /var/run/sshd
/usr/sbin/sshd

# ntp
/etc/init.d/ntp start

# arp tuning
echo 32768 > /proc/sys/net/ipv4/neigh/default/gc_thresh1
echo 32768 > /proc/sys/net/ipv4/neigh/default/gc_thresh2
echo 65536 > /proc/sys/net/ipv4/neigh/default/gc_thresh3
echo 32768 > /proc/sys/net/ipv6/neigh/default/gc_thresh1
echo 32768 > /proc/sys/net/ipv6/neigh/default/gc_thresh2
echo 65536 > /proc/sys/net/ipv6/neigh/default/gc_thresh3

# attach a real tty to the console
setsid sh -c 'exec sh </dev/tty1 >/dev/tty1 2>&1'
