name: Build Binaries
on:
  push:
  workflow_call:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
      name: Build Binaries
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
          with:
            path: minimega
            persist-credentials: false
        - name: Build
          run: |
            sudo apt-get update
            sudo apt-get install -y build-essential dnsmasq iproute2 isc-dhcp-client libpcap-dev ntfs-3g openssh-client openvswitch-switch qemu-kvm qemu-utils
            cd minimega
            ./scripts/all.bash
        # Only for release:
        - name: Tar
          if: github.event_name == 'workflow_dispatch' || github.event_name == 'release'
          run: tar -czvf minimega-$( cat minimega/VERSION | cut -d'=' -f2 )-binaries.tar.gz minimega
        - name: Upload artifact
          uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
          if: github.event_name == 'workflow_dispatch' || github.event_name == 'release'
          with:
            name: minimega-binaries
            path: ./*.tar.gz
        - name: Upload python package
          uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
          if: github.event_name == 'workflow_dispatch' || github.event_name == 'release'
          with:
            name: minimega-python-dist
            path: ./minimega/lib/dist/
