name: Publish Docker image

on:
  push:
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  push-to-ghcr:
    name: Build ${{ matrix.target }} Docker image
    runs-on: ubuntu-latest
    timeout-minutes: 60
    concurrency:
      group: docker-${{ matrix.target }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: ${{ github.event_name == 'pull_request' }}
    permissions:
      packages: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: minimega
            image: ghcr.io/${{ github.repository }}
            description: minimega is a tool for launching and managing virtual machines
          - target: miniweb
            image: ghcr.io/${{ github.repository_owner }}/miniweb
            description: miniweb is the web interface for minimega
    steps:
      - name: Check out the repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ matrix.image }}
          labels: |
            org.opencontainers.image.vendor=Sandia National Laboratories
            org.opencontainers.image.authors=minimega dev team <minimega-dev@sandia.gov>
            org.opencontainers.image.title=${{ matrix.target }}
            org.opencontainers.image.url=https://sandia-minimega.github.io/minimega/
            org.opencontainers.image.documentation=https://sandia-minimega.github.io/minimega/
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.description=${{ matrix.description }}
            org.opencontainers.image.licenses=GPL-3.0
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,prefix=,suffix=,format=short
      - name: Log in to GitHub Container Registry
        if: github.event_name == 'push'
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container image
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
        with:
          context: .
          file: docker/Dockerfile
          target: ${{ matrix.target }}
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
