name: Publish Docker image
on: [push]
jobs:
  push-to-ghcr:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Get short SHA
        id: short
        run: |
          echo "::set-output name=sha::$(git rev-parse --short HEAD)"
          echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=mmversion::$(cat VERSION)"
          echo "::set-output name=buildtime::$(date -I'seconds')"
          echo "::set-output name=repolowercase::$(echo ${GITHUB_REPOSITORY,,})"
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          build-args: |
            MM_COMMIT=${{ github.sha }}
            MM_VERSION=${{ steps.short.outputs.mmversion }}
            BUILD_TIME=$${ steps.short.outputs.buildtime }}
          push: true
          tags: |
            ghcr.io/${{ steps.short.outputs.repolowercase }}/minimega:${{ steps.short.outputs.sha }}
            ghcr.io/${{ steps.short.outputs.repolowercase }}/minimega:${{ steps.short.outputs.branch }}
